[workspace]
resolver = "2"
members = [
    "crates/malu-interfaces",
    "crates/malu-core",
    "crates/malu-storage",
    "crates/malu-crypto",
    "crates/malu-auth",
    "crates/malu-api",
    "crates/malu-app",
    "crates/malu-cli",
    "crates/malu-event",
    "crates/malu-governance",
    "crates/malu-hsm",
    "crates/malu-k8s",
    "crates/malu-observability",
    "crates/malu-recovery",
]

[workspace.dependencies]
tokio = { version = "1.32.0", features = ["full", "test-util", "macros", "rt-multi-thread"] }
tracing = "0.1.37"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
thiserror = "1.0.43"
anyhow = "1.0.72"
async-trait = { version = "0.1.74" }
log = "0.4.19"
futures = "0.3.28"
uuid = { version = "1.4.1", features = ["v4", "serde"] }
