[workspace]
members = [
    "crates/malu-interfaces",
    "crates/malu-core",
    "crates/malu-storage",
    "crates/malu-crypto",
    "crates/malu-auth",
    "crates/malu-api",
    "crates/malu-app",
    "crates/malu-cli",
    "crates/malu-event",
    "crates/malu-governance",
    "crates/malu-hsm",
    "crates/malu-k8s",
    "crates/malu-observability",
    "crates/malu-recovery",
]

[workspace.dependencies]
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
async-trait = "0.1"
log = "0.4"
futures = "0.3"
uuid = { version = "1.4", features = ["v4", "serde"] }
