apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secret-storage-service-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: secret-storage-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress traffic only from Istio ingress gateway and other authorized services
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
    - podSelector:
        matchLabels:
          app: istio-ingressgateway
    ports:
    - protocol: TCP
      port: 3000  # The app's HTTP port
  # Allow ingress from specific internal services that need to access secrets
  - from:
    - podSelector:
        matchLabels:
          app: auth-service
    - podSelector:
        matchLabels:
          app: api-gateway
    ports:
    - protocol: TCP
      port: 3000
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
  # Allow access to Redis
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  # Allow access to PostgreSQL if used
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  # Allow access to SigNoz/OpenTelemetry collector for telemetry
  - to:
    - namespaceSelector:
        matchLabels:
          name: observability
    - podSelector:
        matchLabels:
          app: signoz-otel-collector
    ports:
    - protocol: TCP
      port: 4317
    - protocol: TCP
      port: 4318
